name: Weltherrschaft
on: [push]
permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install -g yarn
      - run: yarn install
        working-directory: app
      - run: yarn run build
        working-directory: app
      - uses: geekyeggo/delete-artifact@v5 # workarround für einen bug im task upload-pages-artifact
        with:
          name: github-pages
      - name: upload pages files
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/dist
          name: github-pages
      - name: deploy pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
